language: ruby
rvm: 2.1.0
script:
- bundle exec jekyll build
- _scripts/travis_deploy.sh
skip_cleanup: true
sudo: false
cache: bundler
branches:
  only:
  - master
env:
  global:
  - JEKYLL_ENV: production
  - GH_REF: github.com/daviesgeek/daviesgeek.github.io
  - secure: "X0oh44re34eVAHXT9Odz8P7Qjqdn6Cq4FmZ3LQ5LDW7DBvE8Wi+ZZJnRwycuWVHqgJmHksVEKdtdE2FGofA7GxnkoDdcj96jlKh6yC1CMI7lo0Tbow8z2sF7v8Q4I9YMm/MfkhZUoRxyDZjmTzp3vr5/ql3qdguwrt2IIaKG69A="