permalink: "/:year/:month/:title"
name: "daviesgeek.com"
description: "Blog about technology, programming, and other related topics"
exclude:
  - _helpers
baseurl: "http://daviesgeek.com"
gems:
  - jekyll-sitemap
paginate: 35
paginate_path: "posts/:num"
timezone: America/Los_Angeles
markdown: kramdown
